name: CI Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build gateway image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: CI/dockerfiles/Dockerfile.gateway
          push: false
          tags: tether/gateway:pilot
      - name: Build orchestrator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: CI/dockerfiles/Dockerfile.orchestrator
          push: false
          tags: tether/orchestrator:pilot
      - name: Build registry image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: CI/dockerfiles/Dockerfile.registry
          push: false
          tags: tether/registry:pilot
      - name: Build worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: CI/dockerfiles/Dockerfile.worker
          push: false
          tags: tether/worker:pilot