name: CI Lint, Build, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ gateway, orchestrator, registry ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd services/${{ matrix.service }}
          npm install
      - name: Lint (ESLint StandardJS)
        run: |
          cd services/${{ matrix.service }}
          npx eslint .
      - name: Build TypeScript
        run: |
          cd services/${{ matrix.service }}
          npx tsc --noEmit false

  python-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/worker/requirements.txt
      - name: Lint (flake8)
        run: |
          python -m flake8 services/worker/src