{
 "title": "Worker Inference",
 "tags": [ "haif" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Inference requests per second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(infer_requests_total[1m])) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Inference failures per second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(infer_failures_total[1m])) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Inference duration P95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(infer_duration_seconds_bucket[5m])) by (le, model))",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}