global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_by: ['alertname','service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://gateway:3000/health' # placeholder webhook; replace in production