receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}
  resource:
    attributes:
      - key: deployment.environment
        action: upsert
        value: ${NODE_ENV}

exporters:
  otlphttp:
    endpoint: http://jaeger:4318
    traces_endpoint: /v1/traces

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlphttp]