global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:9464"]
  - job_name: orchestrator
    static_configs:
      - targets: ["orchestrator:9464"]
  - job_name: registry
    static_configs:
      - targets: ["registry:9464"]
  - job_name: worker
    static_configs:
      - targets: ["worker:9464"]