name: CI Lint, Build, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ gateway, orchestrator, registry, worker ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: services/${{ matrix.service }}/package-lock.json
      - name: Install dependencies
        working-directory: services/${{ matrix.service }}
        run: npm install
      - name: Lint
        working-directory: services/${{ matrix.service }}
        run: npm run lint
      - name: Build
        working-directory: services/${{ matrix.service }}
        run: npm run build
